Category.create! name: "未分類"
Category.create! name: "公園"
Category.create! name: "運動場地"
Category.create! name: "婚宴場地"
Category.create! name: "展演中心"
Category.create! name: "校園"
Category.create! name: "戶外空地"
Category.create! name: "公司大樓"